# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2444ba12292d0081029796484867d8f0cc96dca4914e710888a86e9cb3f88ffecdba818a01d5aede95d81e3befe581f81bbd5456370ad625dbf35ba61de76d30

test:
  secret_key_base: 94e7849855e629dedef9d0bb7db9071ae25ae728264e727474c7213dc9601b3d6692e3ed99f39773b344e501f55a8f886b4542708e6676829141c33048a5203c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
